import { CanonicalBoardDefinition } from './types';

export const ArduinoUno: CanonicalBoardDefinition = {
  id: 'arduino_uno',
  name: 'Arduino Uno',
  manufacturer: 'Arduino',
  targetId: 'arduino_uno',
  mcuId: 'atmega328p',
  architecture: 'avr',
  mcu: 'ATmega328P',
  frequency: '16MHz',
  pins: {
    D0: { id: 'D0', label: 'RX0', physicalNumber: 0, capabilities: ['digital', 'digital_in', 'digital_out', 'uart_rx'], voltage: '5V', isReserved: true, warningMessage: 'Reserved for Serial RX / Programming' },
    D1: { id: 'D1', label: 'TX1', physicalNumber: 1, capabilities: ['digital', 'digital_in', 'digital_out', 'uart_tx'], voltage: '5V', isReserved: true, warningMessage: 'Reserved for Serial TX / Programming' },
    D2: { id: 'D2', label: 'D2', physicalNumber: 2, capabilities: ['digital', 'digital_in', 'digital_out', 'interrupt'], voltage: '5V' },
    D3: { id: 'D3', label: 'D3 ~', physicalNumber: 3, capabilities: ['digital', 'digital_in', 'digital_out', 'pwm', 'interrupt'], voltage: '5V' },
    D4: { id: 'D4', label: 'D4', physicalNumber: 4, capabilities: ['digital', 'digital_in', 'digital_out'], voltage: '5V' },
    D5: { id: 'D5', label: 'D5 ~', physicalNumber: 5, capabilities: ['digital', 'digital_in', 'digital_out', 'pwm'], voltage: '5V' },
    D6: { id: 'D6', label: 'D6 ~', physicalNumber: 6, capabilities: ['digital', 'digital_in', 'digital_out', 'pwm'], voltage: '5V' },
    D7: { id: 'D7', label: 'D7', physicalNumber: 7, capabilities: ['digital', 'digital_in', 'digital_out'], voltage: '5V' },
    D8: { id: 'D8', label: 'D8', physicalNumber: 8, capabilities: ['digital', 'digital_in', 'digital_out'], voltage: '5V' },
    D9: { id: 'D9', label: 'D9 ~', physicalNumber: 9, capabilities: ['digital', 'digital_in', 'digital_out', 'pwm'], voltage: '5V' },
    D10: { id: 'D10', label: 'D10 ~', physicalNumber: 10, capabilities: ['digital', 'digital_in', 'digital_out', 'pwm', 'spi_cs'], voltage: '5V' },
    D11: { id: 'D11', label: 'D11 ~', physicalNumber: 11, capabilities: ['digital', 'digital_in', 'digital_out', 'pwm', 'spi_mosi'], voltage: '5V' },
    D12: { id: 'D12', label: 'D12', physicalNumber: 12, capabilities: ['digital', 'digital_in', 'digital_out', 'spi_miso'], voltage: '5V' },
    D13: { id: 'D13', label: 'D13', physicalNumber: 13, capabilities: ['digital', 'digital_in', 'digital_out', 'spi_sck'], voltage: '5V' },
    A0: { id: 'A0', label: 'A0', physicalNumber: 14, capabilities: ['analog', 'analog_in', 'digital', 'digital_in', 'digital_out'], voltage: '5V' },
    A1: { id: 'A1', label: 'A1', physicalNumber: 15, capabilities: ['analog', 'analog_in', 'digital', 'digital_in', 'digital_out'], voltage: '5V' },
    A2: { id: 'A2', label: 'A2', physicalNumber: 16, capabilities: ['analog', 'analog_in', 'digital', 'digital_in', 'digital_out'], voltage: '5V' },
    A3: { id: 'A3', label: 'A3', physicalNumber: 17, capabilities: ['analog', 'analog_in', 'digital', 'digital_in', 'digital_out'], voltage: '5V' },
    A4: { id: 'A4', label: 'A4 / SDA', physicalNumber: 18, capabilities: ['analog', 'analog_in', 'digital', 'digital_in', 'digital_out', 'i2c_sda'], voltage: '5V' },
    A5: { id: 'A5', label: 'A5 / SCL', physicalNumber: 19, capabilities: ['analog', 'analog_in', 'digital', 'digital_in', 'digital_out', 'i2c_scl'], voltage: '5V' },
    '5V': { id: '5V', label: '5V', capabilities: ['power', 'power_5v'], voltage: '5V' },
    '3.3V': { id: '3.3V', label: '3.3V', capabilities: ['power', 'power_3v3'], voltage: '3.3V' },
    GND: { id: 'GND', label: 'GND', capabilities: ['ground'] },
    VIN: { id: 'VIN', label: 'VIN', capabilities: ['power', 'power_vin'] },
  },
  buses: {
    i2c: {
      sda: 'A4',
      scl: 'A5',
    },
    spi: {
      miso: 'D12',
      mosi: 'D11',
      sck: 'D13',
    },
    uart: {
      tx: 'D1',
      rx: 'D0',
      baudRate: 9600,
    },
  },
  defaultLayout: {
    width: 290,
    height: 380,
    pinGroups: [
      { name: 'Digital', side: 'right', pinIds: ['D13', 'D12', 'D11', 'D10', 'D9', 'D8', 'D7', 'D6', 'D5', 'D4', 'D3', 'D2', 'D1', 'D0'] },
      { name: 'Analog', side: 'left', pinIds: ['A0', 'A1', 'A2', 'A3', 'A4', 'A5'] },
      { name: 'Power', side: 'left', pinIds: ['VIN', '5V', '3.3V', 'GND'] },
    ],
  },
};
