import { CanonicalBoardDefinition } from './types';

export const ArduinoMega2560: CanonicalBoardDefinition = {
  id: 'arduino_mega_2560',
  name: 'Arduino Mega 2560',
  manufacturer: 'Arduino',
  targetId: 'arduino_mega',
  mcuId: 'atmega2560',
  architecture: 'avr',
  mcu: 'ATmega2560',
  frequency: '16MHz',
  pins: {
    D0: { id: 'D0', label: 'RX0', physicalNumber: 0, capabilities: ['digital', 'digital_in', 'digital_out', 'uart_rx'], voltage: '5V', isReserved: true },
    D1: { id: 'D1', label: 'TX0', physicalNumber: 1, capabilities: ['digital', 'digital_in', 'digital_out', 'uart_tx'], voltage: '5V', isReserved: true },
    D2: { id: 'D2', label: 'D2 ~', physicalNumber: 2, capabilities: ['digital', 'digital_in', 'digital_out', 'pwm', 'interrupt'], voltage: '5V' },
    D3: { id: 'D3', label: 'D3 ~', physicalNumber: 3, capabilities: ['digital', 'digital_in', 'digital_out', 'pwm', 'interrupt'], voltage: '5V' },
    D4: { id: 'D4', label: 'D4 ~', physicalNumber: 4, capabilities: ['digital', 'digital_in', 'digital_out', 'pwm'], voltage: '5V' },
    D5: { id: 'D5', label: 'D5 ~', physicalNumber: 5, capabilities: ['digital', 'digital_in', 'digital_out', 'pwm'], voltage: '5V' },
    D6: { id: 'D6', label: 'D6 ~', physicalNumber: 6, capabilities: ['digital', 'digital_in', 'digital_out', 'pwm'], voltage: '5V' },
    D7: { id: 'D7', label: 'D7 ~', physicalNumber: 7, capabilities: ['digital', 'digital_in', 'digital_out', 'pwm'], voltage: '5V' },
    D8: { id: 'D8', label: 'D8 ~', physicalNumber: 8, capabilities: ['digital', 'digital_in', 'digital_out', 'pwm'], voltage: '5V' },
    D9: { id: 'D9', label: 'D9 ~', physicalNumber: 9, capabilities: ['digital', 'digital_in', 'digital_out', 'pwm'], voltage: '5V' },
    D10: { id: 'D10', label: 'D10 ~', physicalNumber: 10, capabilities: ['digital', 'digital_in', 'digital_out', 'pwm'], voltage: '5V' },
    D11: { id: 'D11', label: 'D11 ~', physicalNumber: 11, capabilities: ['digital', 'digital_in', 'digital_out', 'pwm'], voltage: '5V' },
    D12: { id: 'D12', label: 'D12 ~', physicalNumber: 12, capabilities: ['digital', 'digital_in', 'digital_out', 'pwm'], voltage: '5V' },
    D13: { id: 'D13', label: 'D13 ~', physicalNumber: 13, capabilities: ['digital', 'digital_in', 'digital_out', 'pwm'], voltage: '5V' },
    D18: { id: 'D18', label: 'TX1 / D18', physicalNumber: 18, capabilities: ['digital', 'digital_in', 'digital_out', 'uart_tx', 'interrupt'], voltage: '5V' },
    D19: { id: 'D19', label: 'RX1 / D19', physicalNumber: 19, capabilities: ['digital', 'digital_in', 'digital_out', 'uart_rx', 'interrupt'], voltage: '5V' },
    D20: { id: 'D20', label: 'SDA / D20', physicalNumber: 20, capabilities: ['digital', 'digital_in', 'digital_out', 'i2c_sda', 'interrupt'], voltage: '5V' },
    D21: { id: 'D21', label: 'SCL / D21', physicalNumber: 21, capabilities: ['digital', 'digital_in', 'digital_out', 'i2c_scl', 'interrupt'], voltage: '5V' },
    D50: { id: 'D50', label: 'MISO / D50', physicalNumber: 50, capabilities: ['digital', 'digital_in', 'digital_out', 'spi_miso'], voltage: '5V' },
    D51: { id: 'D51', label: 'MOSI / D51', physicalNumber: 51, capabilities: ['digital', 'digital_in', 'digital_out', 'spi_mosi'], voltage: '5V' },
    D52: { id: 'D52', label: 'SCK / D52', physicalNumber: 52, capabilities: ['digital', 'digital_in', 'digital_out', 'spi_sck'], voltage: '5V' },
    D53: { id: 'D53', label: 'SS / D53', physicalNumber: 53, capabilities: ['digital', 'digital_in', 'digital_out', 'spi_cs'], voltage: '5V' },
    A0: { id: 'A0', label: 'A0', physicalNumber: 54, capabilities: ['analog', 'analog_in', 'digital', 'digital_in', 'digital_out'], voltage: '5V' },
    A1: { id: 'A1', label: 'A1', physicalNumber: 55, capabilities: ['analog', 'analog_in', 'digital', 'digital_in', 'digital_out'], voltage: '5V' },
    A2: { id: 'A2', label: 'A2', physicalNumber: 56, capabilities: ['analog', 'analog_in', 'digital', 'digital_in', 'digital_out'], voltage: '5V' },
    A3: { id: 'A3', label: 'A3', physicalNumber: 57, capabilities: ['analog', 'analog_in', 'digital', 'digital_in', 'digital_out'], voltage: '5V' },
    A4: { id: 'A4', label: 'A4', physicalNumber: 58, capabilities: ['analog', 'analog_in', 'digital', 'digital_in', 'digital_out'], voltage: '5V' },
    A5: { id: 'A5', label: 'A5', physicalNumber: 59, capabilities: ['analog', 'analog_in', 'digital', 'digital_in', 'digital_out'], voltage: '5V' },
    '5V': { id: '5V', label: '5V', capabilities: ['power', 'power_5v'], voltage: '5V' },
    '3.3V': { id: '3.3V', label: '3.3V', capabilities: ['power', 'power_3v3'], voltage: '3.3V' },
    GND: { id: 'GND', label: 'GND', capabilities: ['ground'] },
    VIN: { id: 'VIN', label: 'VIN', capabilities: ['power', 'power_vin'] },
  },
  buses: {
    i2c: {
      sda: 'D20',
      scl: 'D21',
    },
    spi: {
      miso: 'D50',
      mosi: 'D51',
      sck: 'D52',
    },
    uart: {
      tx: 'D1',
      rx: 'D0',
      baudRate: 9600,
    },
  },
  defaultLayout: {
    width: 320,
    height: 480,
    pinGroups: [
      { name: 'PWM & Digital', side: 'right', pinIds: ['D13', 'D12', 'D11', 'D10', 'D9', 'D8', 'D7', 'D6', 'D5', 'D4', 'D3', 'D2', 'D1', 'D0'] },
      { name: 'Communication', side: 'right', pinIds: ['D21', 'D20', 'D19', 'D18', 'D53', 'D52', 'D51', 'D50'] },
      { name: 'Analog', side: 'left', pinIds: ['A0', 'A1', 'A2', 'A3', 'A4', 'A5'] },
      { name: 'Power', side: 'left', pinIds: ['VIN', '5V', '3.3V', 'GND'] },
    ],
  },
};
