import { CanonicalBoardDefinition } from './types';

export const ESP32: CanonicalBoardDefinition = {
  id: 'esp32',
  name: 'ESP32 DevKitC',
  manufacturer: 'Espressif',
  targetId: 'esp32_arduino',
  mcuId: 'esp32_wroom_32',
  architecture: 'xtensa_lx6',
  mcu: 'ESP32-WROOM-32',
  frequency: '240MHz',
  pins: {
    GPIO0: { id: 'GPIO0', label: 'IO0', capabilities: ['digital', 'digital_in', 'digital_out', 'pwm', 'touch'], voltage: '3.3V', isStrappingPin: true, warningMessage: 'Boot strapping pin (pull LOW to enter download mode)' },
    GPIO2: { id: 'GPIO2', label: 'IO2', capabilities: ['digital', 'digital_in', 'digital_out', 'pwm', 'touch'], voltage: '3.3V', isStrappingPin: true },
    GPIO4: { id: 'GPIO4', label: 'IO4', capabilities: ['digital', 'digital_in', 'digital_out', 'analog', 'analog_in', 'pwm', 'touch'], voltage: '3.3V' },
    GPIO12: { id: 'GPIO12', label: 'IO12', capabilities: ['digital', 'digital_in', 'digital_out', 'analog', 'analog_in', 'pwm', 'touch', 'spi_miso'], voltage: '3.3V', isStrappingPin: true },
    GPIO13: { id: 'GPIO13', label: 'IO13', capabilities: ['digital', 'digital_in', 'digital_out', 'analog', 'analog_in', 'pwm', 'touch', 'spi_mosi'], voltage: '3.3V' },
    GPIO14: { id: 'GPIO14', label: 'IO14', capabilities: ['digital', 'digital_in', 'digital_out', 'analog', 'analog_in', 'pwm', 'touch', 'spi_sck'], voltage: '3.3V' },
    GPIO15: { id: 'GPIO15', label: 'IO15', capabilities: ['digital', 'digital_in', 'digital_out', 'analog', 'analog_in', 'pwm', 'touch'], voltage: '3.3V', isStrappingPin: true },
    GPIO18: { id: 'GPIO18', label: 'IO18', capabilities: ['digital', 'digital_in', 'digital_out', 'pwm', 'spi_sck'], voltage: '3.3V' },
    GPIO19: { id: 'GPIO19', label: 'IO19', capabilities: ['digital', 'digital_in', 'digital_out', 'pwm', 'spi_miso'], voltage: '3.3V' },
    GPIO21: { id: 'GPIO21', label: 'IO21 / SDA', capabilities: ['digital', 'digital_in', 'digital_out', 'i2c_sda'], voltage: '3.3V' },
    GPIO22: { id: 'GPIO22', label: 'IO22 / SCL', capabilities: ['digital', 'digital_in', 'digital_out', 'i2c_scl'], voltage: '3.3V' },
    GPIO23: { id: 'GPIO23', label: 'IO23', capabilities: ['digital', 'digital_in', 'digital_out', 'pwm', 'spi_mosi'], voltage: '3.3V' },
    GPIO25: { id: 'GPIO25', label: 'IO25 / DAC1', capabilities: ['digital', 'digital_in', 'digital_out', 'analog', 'analog_in', 'analog_out', 'dac', 'pwm'], voltage: '3.3V' },
    GPIO26: { id: 'GPIO26', label: 'IO26 / DAC2', capabilities: ['digital', 'digital_in', 'digital_out', 'analog', 'analog_in', 'analog_out', 'dac', 'pwm'], voltage: '3.3V' },
    GPIO27: { id: 'GPIO27', label: 'IO27', capabilities: ['digital', 'digital_in', 'digital_out', 'analog', 'analog_in', 'pwm', 'touch'], voltage: '3.3V' },
    GPIO32: { id: 'GPIO32', label: 'IO32', capabilities: ['digital', 'digital_in', 'digital_out', 'analog', 'analog_in', 'touch'], voltage: '3.3V' },
    GPIO33: { id: 'GPIO33', label: 'IO33', capabilities: ['digital', 'digital_in', 'digital_out', 'analog', 'analog_in', 'touch'], voltage: '3.3V' },
    GPIO34: { id: 'GPIO34', label: 'IO34 (Input)', capabilities: ['analog', 'analog_in', 'digital_in'], voltage: '3.3V', warningMessage: 'Input only — no output driver' },
    GPIO35: { id: 'GPIO35', label: 'IO35 (Input)', capabilities: ['analog', 'analog_in', 'digital_in'], voltage: '3.3V', warningMessage: 'Input only — no output driver' },
    GPIO36: { id: 'GPIO36', label: 'VP / IO36', capabilities: ['analog', 'analog_in', 'digital_in'], voltage: '3.3V', warningMessage: 'Input only (ADC1 CH0)' },
    GPIO39: { id: 'GPIO39', label: 'VN / IO39', capabilities: ['analog', 'analog_in', 'digital_in'], voltage: '3.3V', warningMessage: 'Input only (ADC1 CH3)' },
    '5V': { id: '5V', label: '5V', capabilities: ['power', 'power_5v'], voltage: '5V' },
    '3.3V': { id: '3.3V', label: '3.3V', capabilities: ['power', 'power_3v3'], voltage: '3.3V' },
    GND: { id: 'GND', label: 'GND', capabilities: ['ground'] },
  },
  buses: {
    i2c: {
      sda: 'GPIO21',
      scl: 'GPIO22',
    },
    spi: {
      miso: 'GPIO19',
      mosi: 'GPIO23',
      sck: 'GPIO18',
    },
    uart: {
      tx: 'GPIO1',
      rx: 'GPIO3',
      baudRate: 115200,
    },
  },
  defaultLayout: {
    width: 320,
    height: 420,
    pinGroups: [
      { name: 'Left Header', side: 'left', pinIds: ['3.3V', 'GPIO36', 'GPIO39', 'GPIO34', 'GPIO35', 'GPIO32', 'GPIO33', 'GPIO25', 'GPIO26', 'GPIO27', 'GPIO14', 'GPIO12', 'GND'] },
      { name: 'Right Header', side: 'right', pinIds: ['5V', 'GPIO23', 'GPIO22', 'GPIO1', 'GPIO3', 'GPIO21', 'GPIO19', 'GPIO18', 'GPIO5', 'GPIO17', 'GPIO16', 'GPIO4', 'GPIO0', 'GPIO2', 'GPIO15'] },
    ],
  },
};
