import { FlowSettings } from './types'

export const DEFAULT_SETTINGS: FlowSettings = {
  general: {
    startupWorkspace: 'editor',
    autoSave: true,
    autoSaveIntervalMs: 5000,
    checkForUpdates: true,
    confirmUnsaved: true,
    recentLimit: 10,
  },
  appearance: {
    theme: 'dark',
    accentColor: 'blue',
    uiScale: 100,
    compactMode: false,
    reduceMotion: false,
  },
  editor: {
    explorerWidth: 260,
    propertiesWidth: 280,
    bottomPanelHeight: 220,
    showMinimap: true,
    autoExpandPanels: true,
    rememberPanelSizes: true,
  },
  canvas: {
    showGrid: true,
    snapToGrid: true,
    gridDensity: 20,
    zoomSensitivity: 1.0,
    panSpeed: 1.0,
    smoothZoom: true,
    smoothNodeAnimation: true,
    edgeStyle: 'bezier',
    connectionPreview: true,
  },
  compiler: {
    defaultBoard: 'arduino_uno',
    optimizationLevel: 'O2',
    generateComments: true,
    codeFormatting: true,
    verboseOutput: false,
    outputFolder: 'build',
  },
  simulation: {
    simulationSpeed: 1.0,
    autoResetMCU: true,
    liveGpioPreview: true,
    serialMonitorAutoOpen: true,
    simulationTimeout: 30,
  },
  keybindings: [
    { id: 'duplicate_node', label: 'Duplicate Selected Node', category: 'Canvas', keys: 'Ctrl + D' },
    { id: 'delete_node', label: 'Delete Selected Node', category: 'Canvas', keys: 'Delete / Backspace' },
    { id: 'undo', label: 'Undo Action', category: 'Edit', keys: 'Ctrl + Z' },
    { id: 'redo', label: 'Redo Action', category: 'Edit', keys: 'Ctrl + Y / Shift + Ctrl + Z' },
    { id: 'copy_node', label: 'Copy Node', category: 'Edit', keys: 'Ctrl + C' },
    { id: 'cut_node', label: 'Cut Node', category: 'Edit', keys: 'Ctrl + X' },
    { id: 'paste_node', label: 'Paste Node', category: 'Edit', keys: 'Ctrl + V' },
    { id: 'open_preferences', label: 'Open Preferences', category: 'Global', keys: 'Ctrl + ,' },
    { id: 'reset_view', label: 'Reset Canvas Zoom & View', category: 'Canvas', keys: 'Ctrl + 0' },
    { id: 'toggle_code', label: 'Toggle Code Output Panel', category: 'View', keys: 'Ctrl + Shift + C' },
  ],
  extensions: [
    {
      id: 'arduino-core',
      name: 'Arduino Core Toolchain',
      version: '1.8.19',
      description: 'Standard AVR cross-compiler and firmware uploader for ATmega boards.',
      author: 'Flow-IDE Team',
      installed: true,
      enabled: true,
    },
    {
      id: 'esp32-extension',
      name: 'ESP32 Hardware Support',
      version: '2.0.11',
      description: 'Xtensa toolchain, FreeRTOS SDK, and Wi-Fi stack for ESP32 & S2/S3/C3 modules.',
      author: 'Flow-IDE Community',
      installed: false,
      enabled: false,
    },
    {
      id: 'sensor-library-pack',
      name: 'Extended Sensor Driver Pack',
      version: '1.2.0',
      description: 'High-precision drivers for DHT22, BME280, MPU6050, and VL53L0X sensors.',
      author: 'Sensors Group',
      installed: true,
      enabled: true,
    },
  ],
}
